[versions]
agp = "8.11.2"
cardview = "1.0.0"
firebaseBom = "34.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
firebaseAuth = "24.0.1"
firebaseFirestore = "26.0.2"
mpandroidchart = "v3.1.0"
recyclerview = "1.4.0"
volley = "1.2.1"

[libraries]
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

